version: "3.7"
services:
  db:
    image: mysql:latest
    ports:
      - "3002:3306"
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DB_DATA}:/var/lib/mysql:rw
    restart: "always"
    container_name: "mysql_blog_db"
